run:
  timeout: 10m

linters:
  enable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - structcheck
    - varcheck

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
